"""empty message

Revision ID: 197f0673e6c3
Revises: b0835d44c266
Create Date: 2023-11-18 21:54:35.431059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197f0673e6c3'
down_revision = 'b0835d44c266'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('department_id', sa.String(length=20), nullable=False, comment='部门编号'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='部门名'),
    sa.PrimaryKeyConstraint('department_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('department')
    # ### end Alembic commands ###
