"""create AttendanceModel

Revision ID: 392ed6b99aef
Revises: 197f0673e6c3
Create Date: 2023-11-20 16:23:19.645871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392ed6b99aef'
down_revision = '197f0673e6c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.String(length=20), nullable=False, comment='出勤信息主键id'),
    sa.Column('uid', sa.String(length=20), nullable=False, comment='归属用户id'),
    sa.Column('time', sa.String(length=20), nullable=False, comment='归属月份'),
    sa.Column('work_cnt', sa.SmallInteger(), nullable=False, comment='出勤天数'),
    sa.Column('work_days', sa.String(length=20), nullable=False, comment='出勤日期列表'),
    sa.Column('memo', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('status', sa.Boolean(), nullable=False, comment='出勤信息是否提交'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance')
    # ### end Alembic commands ###
