"""empty message

Revision ID: 4e64d2c16618
Revises: 392ed6b99aef
Create Date: 2023-11-20 16:51:50.172984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4e64d2c16618'
down_revision = '392ed6b99aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('work_days',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Text(),
               existing_comment='出勤日期列表',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('work_days',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=20),
               existing_comment='出勤日期列表',
               existing_nullable=False)

    # ### end Alembic commands ###
