"""empty message

Revision ID: a42f5ef53805
Revises: 4e64d2c16618
Create Date: 2023-11-20 16:56:18.319055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a42f5ef53805'
down_revision = '4e64d2c16618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_comment='出勤信息主键id',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=20),
               existing_comment='出勤信息主键id',
               existing_nullable=False)

    # ### end Alembic commands ###
