"""empty message

Revision ID: a7531520108f
Revises: a42f5ef53805
Create Date: 2023-11-20 17:13:52.945975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7531520108f'
down_revision = 'a42f5ef53805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department_id', sa.String(length=20), nullable=False, comment='归属部门编号'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_column('department_id')

    # ### end Alembic commands ###
