"""修改用户与该表之间的一对一关系

Revision ID: dac69e7b8cfb
Revises: f1461e6b9571
Create Date: 2023-11-28 17:03:17.361920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dac69e7b8cfb'
down_revision = 'f1461e6b9571'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.alter_column('expire_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.alter_column('expire_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###
