"""empty message

Revision ID: e5282f710d83
Revises: dd8319ae5c9b
Create Date: 2023-11-28 20:00:03.406715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5282f710d83'
down_revision = 'dd8319ae5c9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.alter_column('login_time',
               existing_type=mysql.DATETIME(),
               comment='用户登录时间',
               existing_nullable=True)
        batch_op.alter_column('expire_time',
               existing_type=mysql.DATETIME(),
               comment='token过期时间',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.alter_column('expire_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='token过期时间',
               existing_nullable=True)
        batch_op.alter_column('login_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='用户登录时间',
               existing_nullable=True)

    # ### end Alembic commands ###
