"""添加user_token表 并建立用户与该表之间的一对一关系

Revision ID: f1461e6b9571
Revises: 6843681ac9db
Create Date: 2023-11-27 22:01:20.619786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1461e6b9571'
down_revision = '6843681ac9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_token',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('expire_time', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.String(length=20), nullable=False, comment='归属用户id'),
    sa.ForeignKeyConstraint(['uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_token')
    # ### end Alembic commands ###
